# These variables define the project; they may not need to be changed
project:
  type: book
  output-dir: _book

# These variables define the book contents - adjust them as necessary
book:
  # [A] BOOK TITLE
  title: "BM327 Workshop 2: Identifying UTI Adhesion Factors"
  reader-mode: true
  
  # The cover image and favicon; these may not need to be changed
  cover-image: sipbs_compbio_800.png
  favicon: icon_32.png
  
  # Sets the page footer text/images
  # [B] FOOTER TEXT
  page-footer:
    left: |
      These BM327 workshop materials were written by Leighton Pritchard and Morgan Feeney
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  # Sets the URL for the repository
  # [C] GITHUB REPOSITORY URL
  repo-url: https://github.com/sipbs-compbiol/bm327-workshop-2
  repo-branch: main
  repo-actions: [edit, issue]

  # Sets author information and publication/presentation date
  # [D] AUTHOR INFORMATION AND PUBLICATION/PRESENTATION DATE
  author: "Dr Leighton Pritchard and Dr Morgan Feeney"
  date: "03/21/25"

  # Define chapters and sections here
  # [E] CHAPTERS AND SECTIONS
  chapters:
    - index.qmd
    
    - part: part_00_ggplot.qmd
      chapters:
      - ggplot.qmd
    
    - part: part_01_experiment.qmd
      chapters:
      - intro.qmd
      - experimental_results.qmd

#    - part: using_ggplot2.qmd
#      chapters: 
#        - ggplot2_intro.qmd
    
    - part: part_02_batches.qmd
      chapters: 
        - experiment_2.qmd
        - visualising_batches.qmd
        - modelling_data.qmd
        - eliminating_batches.qmd
    
#    - part: supplementary.qmd
#      chapters:
#        - webr-example.qmd
    
#    - references.qmd

# Location of BibTeX format reference file; may not need to be changed
bibliography: references.bib

# Formatting and theme; may not need to be changed
format:
  html:
    theme: cosmo
    code-link: true
    
    author-meta: "Leighton Pritchard"
  
#  pdf:
#    documentclass: scrreprt

# Add custom callouts
custom-callout:
  callout-case-study:
    title: "Case Study"
    icon-symbol: "🔍"
    color: "#FFA500"
  callout-data:
    icon-symbol: "📊"
    title: "Data Analysis"
    color: "#32CD32"
  callout-discussion:
    title: "Discussion Questions:"
    icon-symbol: "✨"
    color: "#BA55D3"
  callout-microbe:
    title: "Microbe Profile"
    icon-symbol: "🧫"
    color: "#1E90FF"
  callout-thumbs-up:
    title: "Great job!"
    icon-symbol: "👍"
    color: "#008000"
  callout-todo:
    icon-symbol: "📝"
    color: "pink"
  callout-challenge:
    title: "Challenge"
    icon-symbol: "🧑‍🏫"
    color: "aquamarine"
  callout-question:
    title: "Question"
    icon-symbol: "🙋"
    color: "yellow"
  callout-questions:
    title: "Questions"
    icon-symbol: "🙋️"
    color: "yellow"    

filters:
  - custom-callout

# Freeze output before pushing modifications to the repository when publishing
# Should not need changing
execute:
  freeze: auto

