# Preface

Welcome to BM327 (Being a Biomolecular Scientist 3) bioinformatics workshop 2 for {{< var ay >}}.

This is the first presentation of this material, and we would be very grateful to hear feedback about it [by email](mailto:{{< var admin.email >}}) or through the [GitHub repository Issues page]({{< var github.issues >}}).

## Overview

This workshop asks you to carry out data analysis and visualisation to identify an adhesion factor important for urinary tract infection.
You will be using the statistical programming language `R` and the widely-used graphics library `ggplot2` to do this.

::: { .callout-warning title="Important Note"}
There is new material in this workshop that is not covered in lectures, and **this material is examinable**. Please take care to read the text in the expandable callout boxes, as well as that for the workshop, to be sure you have understood the topic and obtain full value from the exercise.

The workshop material will remain live online for the duration of BM327, and you can revisit it whenever you wish, for practice or revision.
:::

**You should be able to complete this workshop in under two hours.**

## Learning Objectives

By the end of this workshop, students will be able to:

- Plot experimental data using `R` and `ggplot2`
- Use and interpret box-and-whisker, violin, and 1D scatter plots
- Use linear modelling to estimate effect sizes of biological interventions
- Use linear mixed models to correct for experimental batch effects

## Assessment

This workshop activity itself is not formally assessed although, as noted, all the material it contains is examinable. There is a [formative assessment on MyPlace]({{< var myplace.quiz >}}), which you should complete as part of the workshop.